### ISSUE TITLE
Csound Player - add required sample files? 

### ISSUE THREAD

**Issue by arthunkins** [gogins/csound-extended-manual#4]
Would appreciate your adding all the demo samples, such as fox.wav and beats.wav, to the player repository, allowing more opcode examples from your player reference manual to be performed. Someone on the call today, also mentioned the .htrf files and others perhaps that could allow for other opcode example renderings.

Your player reference manual and Player utility are very helpful, much like the Floss manual's playable examples.

**Comment by gogins** [comment]
This is difficult to do, actually.

The reason is that the Emscripten file system used by the WebAssembly build of filesystem only sees the "local" filesystem on the browser side. The browser itself of course can easily request files from the server filesystem, but the C runtime library used by Csound does not see that... I think.

I'm researching to see if this is doable.

**Comment by gogins** [comment]
What I have found is this. It's possible to embed a sample, a soundfile, a SoundFont, a MIDI file, an image file, an #include file, or indeed any file, and in fact any number of such files, into a .csd file in <CsFIleB filename=file>...</CsFileB> elements of the .csd. The .csd can then be embedded in an HTML file and that can be placed on a local or remote Web server's directory. When Csound compiles the .csd fle, these embedded files are decoded and saved to the local file system, which in this case is the Web browser's protected sandbox or the Android application's private filesystem.

See https://github.com/gogins/csound-ac/issues/27 and https://github.com/gogins/csound-ac/blob/master/vscode-playpen/add2csd.py.
